version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout

      - run: |
          #sudo apt-get update
          #sudo apt-get install -y make gcc libperl-dev wget curl sudo unzip zip git
          #sudo ./build.sh
          #sudo mv exiftool.exe exiftool-amd64-glibc
          sudo mv build.sh exiftool-amd64-glibc

      - persist_to_workspace:
          root: .
          paths:
            - exiftool-amd64-glibc

      - store_artifacts:
          destination: cpanm-log-glibc.zip
          path: cpanm-log.zip

  publish-github-release:
    docker:
      - image: circleci/golang:1.17
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -replace ${CIRCLE_TAG} ./artifacts/

workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/