name: Build glibc binary
on:
  push:
    branches: [ main ]

jobs:
  build-glibc-x64:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: ./build-ubuntu.sh
