name: Build musl binaries

on:
  push:
    tags:
      - '*'

jobs:
  build-glibc-amd64:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: alpine:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: ls && apk add bash && bash build-alpine.sh

      - name: Upload to releases
        uses: svenstaro/upload-release-action@v2
        id: attach_to_release
        with:
          file: exiftool.exe
          asset_name: exiftool-musl-amd64
          tag: ${{ github.ref }}
          overwrite: true
